//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmailpasswordUsers = newEmailpasswordUsersTable("public", "emailpassword_users", "")

type emailpasswordUsersTable struct {
	postgres.Table

	// Columns
	AppID        postgres.ColumnString
	UserID       postgres.ColumnString
	Email        postgres.ColumnString
	PasswordHash postgres.ColumnString
	TimeJoined   postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type EmailpasswordUsersTable struct {
	emailpasswordUsersTable

	EXCLUDED emailpasswordUsersTable
}

// AS creates new EmailpasswordUsersTable with assigned alias
func (a EmailpasswordUsersTable) AS(alias string) *EmailpasswordUsersTable {
	return newEmailpasswordUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmailpasswordUsersTable with assigned schema name
func (a EmailpasswordUsersTable) FromSchema(schemaName string) *EmailpasswordUsersTable {
	return newEmailpasswordUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmailpasswordUsersTable with assigned table prefix
func (a EmailpasswordUsersTable) WithPrefix(prefix string) *EmailpasswordUsersTable {
	return newEmailpasswordUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmailpasswordUsersTable with assigned table suffix
func (a EmailpasswordUsersTable) WithSuffix(suffix string) *EmailpasswordUsersTable {
	return newEmailpasswordUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmailpasswordUsersTable(schemaName, tableName, alias string) *EmailpasswordUsersTable {
	return &EmailpasswordUsersTable{
		emailpasswordUsersTable: newEmailpasswordUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newEmailpasswordUsersTableImpl("", "excluded", ""),
	}
}

func newEmailpasswordUsersTableImpl(schemaName, tableName, alias string) emailpasswordUsersTable {
	var (
		AppIDColumn        = postgres.StringColumn("app_id")
		UserIDColumn       = postgres.StringColumn("user_id")
		EmailColumn        = postgres.StringColumn("email")
		PasswordHashColumn = postgres.StringColumn("password_hash")
		TimeJoinedColumn   = postgres.IntegerColumn("time_joined")
		allColumns         = postgres.ColumnList{AppIDColumn, UserIDColumn, EmailColumn, PasswordHashColumn, TimeJoinedColumn}
		mutableColumns     = postgres.ColumnList{EmailColumn, PasswordHashColumn, TimeJoinedColumn}
	)

	return emailpasswordUsersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AppID:        AppIDColumn,
		UserID:       UserIDColumn,
		Email:        EmailColumn,
		PasswordHash: PasswordHashColumn,
		TimeJoined:   TimeJoinedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
