//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmailpasswordPswdResetTokens = newEmailpasswordPswdResetTokensTable("public", "emailpassword_pswd_reset_tokens", "")

type emailpasswordPswdResetTokensTable struct {
	postgres.Table

	// Columns
	AppID       postgres.ColumnString
	UserID      postgres.ColumnString
	Token       postgres.ColumnString
	Email       postgres.ColumnString
	TokenExpiry postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type EmailpasswordPswdResetTokensTable struct {
	emailpasswordPswdResetTokensTable

	EXCLUDED emailpasswordPswdResetTokensTable
}

// AS creates new EmailpasswordPswdResetTokensTable with assigned alias
func (a EmailpasswordPswdResetTokensTable) AS(alias string) *EmailpasswordPswdResetTokensTable {
	return newEmailpasswordPswdResetTokensTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmailpasswordPswdResetTokensTable with assigned schema name
func (a EmailpasswordPswdResetTokensTable) FromSchema(schemaName string) *EmailpasswordPswdResetTokensTable {
	return newEmailpasswordPswdResetTokensTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmailpasswordPswdResetTokensTable with assigned table prefix
func (a EmailpasswordPswdResetTokensTable) WithPrefix(prefix string) *EmailpasswordPswdResetTokensTable {
	return newEmailpasswordPswdResetTokensTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmailpasswordPswdResetTokensTable with assigned table suffix
func (a EmailpasswordPswdResetTokensTable) WithSuffix(suffix string) *EmailpasswordPswdResetTokensTable {
	return newEmailpasswordPswdResetTokensTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmailpasswordPswdResetTokensTable(schemaName, tableName, alias string) *EmailpasswordPswdResetTokensTable {
	return &EmailpasswordPswdResetTokensTable{
		emailpasswordPswdResetTokensTable: newEmailpasswordPswdResetTokensTableImpl(schemaName, tableName, alias),
		EXCLUDED:                          newEmailpasswordPswdResetTokensTableImpl("", "excluded", ""),
	}
}

func newEmailpasswordPswdResetTokensTableImpl(schemaName, tableName, alias string) emailpasswordPswdResetTokensTable {
	var (
		AppIDColumn       = postgres.StringColumn("app_id")
		UserIDColumn      = postgres.StringColumn("user_id")
		TokenColumn       = postgres.StringColumn("token")
		EmailColumn       = postgres.StringColumn("email")
		TokenExpiryColumn = postgres.IntegerColumn("token_expiry")
		allColumns        = postgres.ColumnList{AppIDColumn, UserIDColumn, TokenColumn, EmailColumn, TokenExpiryColumn}
		mutableColumns    = postgres.ColumnList{EmailColumn, TokenExpiryColumn}
	)

	return emailpasswordPswdResetTokensTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AppID:       AppIDColumn,
		UserID:      UserIDColumn,
		Token:       TokenColumn,
		Email:       EmailColumn,
		TokenExpiry: TokenExpiryColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
