//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type AppIDToUserID struct {
	AppID                    string `sql:"primary_key" json:"app_id" xml:"app_id"`
	UserID                   string `sql:"primary_key" json:"user_id" xml:"user_id"`
	RecipeID                 string `json:"recipe_id" xml:"recipe_id"`
	PrimaryOrRecipeUserID    string `json:"primary_or_recipe_user_id" xml:"primary_or_recipe_user_id"`
	IsLinkedOrIsAPrimaryUser bool   `json:"is_linked_or_is_a_primary_user" xml:"is_linked_or_is_a_primary_user"`
}
