//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Category struct {
	ID        string  `sql:"primary_key" json:"id" xml:"id"`
	UserID    string  `json:"user_id" xml:"user_id"`
	Label     string  `json:"label" xml:"label"`
	Icon      *string `json:"icon" xml:"icon"`
	IsExpense bool    `json:"is_expense" xml:"is_expense"`
	CreatedAt int64   `json:"created_at" xml:"created_at"`
	UpdatedAt int64   `json:"updated_at" xml:"updated_at"`
	LastUsed  int64   `json:"last_used" xml:"last_used"`
}
