//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type DashboardUserSessions struct {
	AppID       string `sql:"primary_key" json:"app_id" xml:"app_id"`
	SessionID   string `sql:"primary_key" json:"session_id" xml:"session_id"`
	UserID      string `json:"user_id" xml:"user_id"`
	TimeCreated int64  `json:"time_created" xml:"time_created"`
	Expiry      int64  `json:"expiry" xml:"expiry"`
}
