//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EmailverificationTokens struct {
	AppID       string `sql:"primary_key" json:"app_id" xml:"app_id"`
	TenantID    string `sql:"primary_key" json:"tenant_id" xml:"tenant_id"`
	UserID      string `sql:"primary_key" json:"user_id" xml:"user_id"`
	Email       string `sql:"primary_key" json:"email" xml:"email"`
	Token       string `sql:"primary_key" json:"token" xml:"token"`
	TokenExpiry int64  `json:"token_expiry" xml:"token_expiry"`
}
