//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type JwtSigningKeys struct {
	AppID     string `sql:"primary_key" json:"app_id" xml:"app_id"`
	KeyID     string `sql:"primary_key" json:"key_id" xml:"key_id"`
	KeyString string `json:"key_string" xml:"key_string"`
	Algorithm string `json:"algorithm" xml:"algorithm"`
	CreatedAt *int64 `json:"created_at" xml:"created_at"`
}
