//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type KeyValue struct {
	AppID         string  `sql:"primary_key" json:"app_id" xml:"app_id"`
	TenantID      string  `sql:"primary_key" json:"tenant_id" xml:"tenant_id"`
	Name          string  `sql:"primary_key" json:"name" xml:"name"`
	Value         *string `json:"value" xml:"value"`
	CreatedAtTime *int64  `json:"created_at_time" xml:"created_at_time"`
}
