//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Roles struct {
	AppID string `sql:"primary_key" json:"app_id" xml:"app_id"`
	Role  string `sql:"primary_key" json:"role" xml:"role"`
}
