//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SessionInfo struct {
	AppID             string  `sql:"primary_key" json:"app_id" xml:"app_id"`
	TenantID          string  `sql:"primary_key" json:"tenant_id" xml:"tenant_id"`
	SessionHandle     string  `sql:"primary_key" json:"session_handle" xml:"session_handle"`
	UserID            string  `json:"user_id" xml:"user_id"`
	RefreshTokenHash2 string  `json:"refresh_token_hash_2" xml:"refresh_token_hash_2"`
	SessionData       *string `json:"session_data" xml:"session_data"`
	ExpiresAt         int64   `json:"expires_at" xml:"expires_at"`
	CreatedAtTime     int64   `json:"created_at_time" xml:"created_at_time"`
	JwtUserPayload    *string `json:"jwt_user_payload" xml:"jwt_user_payload"`
	UseStaticKey      bool    `json:"use_static_key" xml:"use_static_key"`
}
