//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SessionAccessTokenSigningKeys struct {
	AppID         string  `sql:"primary_key" json:"app_id" xml:"app_id"`
	CreatedAtTime int64   `sql:"primary_key" json:"created_at_time" xml:"created_at_time"`
	Value         *string `json:"value" xml:"value"`
}
