//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TenantConfigs struct {
	ConnectionURIDomain  string  `sql:"primary_key" json:"connection_uri_domain" xml:"connection_uri_domain"`
	AppID                string  `sql:"primary_key" json:"app_id" xml:"app_id"`
	TenantID             string  `sql:"primary_key" json:"tenant_id" xml:"tenant_id"`
	CoreConfig           *string `json:"core_config" xml:"core_config"`
	EmailPasswordEnabled *bool   `json:"email_password_enabled" xml:"email_password_enabled"`
	PasswordlessEnabled  *bool   `json:"passwordless_enabled" xml:"passwordless_enabled"`
	ThirdPartyEnabled    *bool   `json:"third_party_enabled" xml:"third_party_enabled"`
}
