//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TenantThirdpartyProviders struct {
	ConnectionURIDomain                          string  `sql:"primary_key" json:"connection_uri_domain" xml:"connection_uri_domain"`
	AppID                                        string  `sql:"primary_key" json:"app_id" xml:"app_id"`
	TenantID                                     string  `sql:"primary_key" json:"tenant_id" xml:"tenant_id"`
	ThirdPartyID                                 string  `sql:"primary_key" json:"third_party_id" xml:"third_party_id"`
	Name                                         *string `json:"name" xml:"name"`
	AuthorizationEndpoint                        *string `json:"authorization_endpoint" xml:"authorization_endpoint"`
	AuthorizationEndpointQueryParams             *string `json:"authorization_endpoint_query_params" xml:"authorization_endpoint_query_params"`
	TokenEndpoint                                *string `json:"token_endpoint" xml:"token_endpoint"`
	TokenEndpointBodyParams                      *string `json:"token_endpoint_body_params" xml:"token_endpoint_body_params"`
	UserInfoEndpoint                             *string `json:"user_info_endpoint" xml:"user_info_endpoint"`
	UserInfoEndpointQueryParams                  *string `json:"user_info_endpoint_query_params" xml:"user_info_endpoint_query_params"`
	UserInfoEndpointHeaders                      *string `json:"user_info_endpoint_headers" xml:"user_info_endpoint_headers"`
	JwksURI                                      *string `json:"jwks_uri" xml:"jwks_uri"`
	OidcDiscoveryEndpoint                        *string `json:"oidc_discovery_endpoint" xml:"oidc_discovery_endpoint"`
	RequireEmail                                 *bool   `json:"require_email" xml:"require_email"`
	UserInfoMapFromIDTokenPayloadUserID          *string `json:"user_info_map_from_id_token_payload_user_id" xml:"user_info_map_from_id_token_payload_user_id"`
	UserInfoMapFromIDTokenPayloadEmail           *string `json:"user_info_map_from_id_token_payload_email" xml:"user_info_map_from_id_token_payload_email"`
	UserInfoMapFromIDTokenPayloadEmailVerified   *string `json:"user_info_map_from_id_token_payload_email_verified" xml:"user_info_map_from_id_token_payload_email_verified"`
	UserInfoMapFromUserInfoEndpointUserID        *string `json:"user_info_map_from_user_info_endpoint_user_id" xml:"user_info_map_from_user_info_endpoint_user_id"`
	UserInfoMapFromUserInfoEndpointEmail         *string `json:"user_info_map_from_user_info_endpoint_email" xml:"user_info_map_from_user_info_endpoint_email"`
	UserInfoMapFromUserInfoEndpointEmailVerified *string `json:"user_info_map_from_user_info_endpoint_email_verified" xml:"user_info_map_from_user_info_endpoint_email_verified"`
}
