//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TenantThirdpartyProviderClients struct {
	ConnectionURIDomain string  `sql:"primary_key" json:"connection_uri_domain" xml:"connection_uri_domain"`
	AppID               string  `sql:"primary_key" json:"app_id" xml:"app_id"`
	TenantID            string  `sql:"primary_key" json:"tenant_id" xml:"tenant_id"`
	ThirdPartyID        string  `sql:"primary_key" json:"third_party_id" xml:"third_party_id"`
	ClientType          string  `sql:"primary_key" json:"client_type" xml:"client_type"`
	ClientID            string  `json:"client_id" xml:"client_id"`
	ClientSecret        *string `json:"client_secret" xml:"client_secret"`
	Scope               *string `json:"scope" xml:"scope"`
	ForcePkce           *bool   `json:"force_pkce" xml:"force_pkce"`
	AdditionalConfig    *string `json:"additional_config" xml:"additional_config"`
}
