//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ThirdpartyUsers struct {
	AppID            string `sql:"primary_key" json:"app_id" xml:"app_id"`
	ThirdPartyID     string `json:"third_party_id" xml:"third_party_id"`
	ThirdPartyUserID string `json:"third_party_user_id" xml:"third_party_user_id"`
	UserID           string `sql:"primary_key" json:"user_id" xml:"user_id"`
	Email            string `json:"email" xml:"email"`
	TimeJoined       int64  `json:"time_joined" xml:"time_joined"`
}
