//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TotpUserDevices struct {
	AppID      string `sql:"primary_key" json:"app_id" xml:"app_id"`
	UserID     string `sql:"primary_key" json:"user_id" xml:"user_id"`
	DeviceName string `sql:"primary_key" json:"device_name" xml:"device_name"`
	SecretKey  string `json:"secret_key" xml:"secret_key"`
	Period     int32  `json:"period" xml:"period"`
	Skew       int32  `json:"skew" xml:"skew"`
	Verified   bool   `json:"verified" xml:"verified"`
}
