//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TotpUsedCodes struct {
	AppID         string `sql:"primary_key" json:"app_id" xml:"app_id"`
	TenantID      string `sql:"primary_key" json:"tenant_id" xml:"tenant_id"`
	UserID        string `sql:"primary_key" json:"user_id" xml:"user_id"`
	Code          string `json:"code" xml:"code"`
	IsValid       bool   `json:"is_valid" xml:"is_valid"`
	ExpiryTimeMs  int64  `json:"expiry_time_ms" xml:"expiry_time_ms"`
	CreatedTimeMs int64  `sql:"primary_key" json:"created_time_ms" xml:"created_time_ms"`
}
