//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Transaction struct {
	ID          string  `sql:"primary_key" json:"id" xml:"id"`
	UserID      string  `json:"user_id" xml:"user_id"`
	Amount      float64 `json:"amount" xml:"amount"`
	Date        int64   `json:"date" xml:"date"`
	CategoryID  string  `json:"category_id" xml:"category_id"`
	Description *string `json:"description" xml:"description"`
	IsExpense   bool    `json:"is_expense" xml:"is_expense"`
	CreatedAt   int64   `json:"created_at" xml:"created_at"`
	UpdatedAt   int64   `json:"updated_at" xml:"updated_at"`
}
