//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type AllAuthRecipeUsers struct {
	AppID                         string `sql:"primary_key"`
	TenantID                      string `sql:"primary_key"`
	UserID                        string `sql:"primary_key"`
	PrimaryOrRecipeUserID         string
	IsLinkedOrIsAPrimaryUser      bool
	RecipeID                      string
	TimeJoined                    int64
	PrimaryOrRecipeUserTimeJoined int64
}
