//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type AppIDToUserID struct {
	AppID                    string `sql:"primary_key"`
	UserID                   string `sql:"primary_key"`
	RecipeID                 string
	PrimaryOrRecipeUserID    string
	IsLinkedOrIsAPrimaryUser bool
}
