//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EmailpasswordPswdResetTokens struct {
	AppID       string `sql:"primary_key"`
	UserID      string `sql:"primary_key"`
	Token       string `sql:"primary_key"`
	Email       *string
	TokenExpiry int64
}
