//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Expense struct {
	ID          string `sql:"primary_key"`
	UserID      string
	Amount      float64
	Date        int64
	Category    string
	Description *string
	CreatedAt   int64
}
