//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PasswordlessCodes struct {
	AppID        string `sql:"primary_key"`
	TenantID     string `sql:"primary_key"`
	CodeID       string `sql:"primary_key"`
	DeviceIDHash string
	LinkCodeHash string
	CreatedAt    int64
}
