//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PasswordlessDevices struct {
	AppID          string `sql:"primary_key"`
	TenantID       string `sql:"primary_key"`
	DeviceIDHash   string `sql:"primary_key"`
	Email          *string
	PhoneNumber    *string
	LinkCodeSalt   string
	FailedAttempts int32
}
