//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SessionInfo struct {
	AppID             string `sql:"primary_key"`
	TenantID          string `sql:"primary_key"`
	SessionHandle     string `sql:"primary_key"`
	UserID            string
	RefreshTokenHash2 string
	SessionData       *string
	ExpiresAt         int64
	CreatedAtTime     int64
	JwtUserPayload    *string
	UseStaticKey      bool
}
