//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TenantThirdpartyProviders struct {
	ConnectionURIDomain                          string `sql:"primary_key"`
	AppID                                        string `sql:"primary_key"`
	TenantID                                     string `sql:"primary_key"`
	ThirdPartyID                                 string `sql:"primary_key"`
	Name                                         *string
	AuthorizationEndpoint                        *string
	AuthorizationEndpointQueryParams             *string
	TokenEndpoint                                *string
	TokenEndpointBodyParams                      *string
	UserInfoEndpoint                             *string
	UserInfoEndpointQueryParams                  *string
	UserInfoEndpointHeaders                      *string
	JwksURI                                      *string
	OidcDiscoveryEndpoint                        *string
	RequireEmail                                 *bool
	UserInfoMapFromIDTokenPayloadUserID          *string
	UserInfoMapFromIDTokenPayloadEmail           *string
	UserInfoMapFromIDTokenPayloadEmailVerified   *string
	UserInfoMapFromUserInfoEndpointUserID        *string
	UserInfoMapFromUserInfoEndpointEmail         *string
	UserInfoMapFromUserInfoEndpointEmailVerified *string
}
