//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TenantThirdpartyProviderClients struct {
	ConnectionURIDomain string `sql:"primary_key"`
	AppID               string `sql:"primary_key"`
	TenantID            string `sql:"primary_key"`
	ThirdPartyID        string `sql:"primary_key"`
	ClientType          string `sql:"primary_key"`
	ClientID            string
	ClientSecret        *string
	Scope               *string
	ForcePkce           *bool
	AdditionalConfig    *string
}
