//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TenantConfigs struct {
	ConnectionURIDomain  string `sql:"primary_key"`
	AppID                string `sql:"primary_key"`
	TenantID             string `sql:"primary_key"`
	CoreConfig           *string
	EmailPasswordEnabled *bool
	PasswordlessEnabled  *bool
	ThirdPartyEnabled    *bool
}
