//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TotpUsedCodes struct {
	AppID         string `sql:"primary_key"`
	TenantID      string `sql:"primary_key"`
	UserID        string `sql:"primary_key"`
	Code          string
	IsValid       bool
	ExpiryTimeMs  int64
	CreatedTimeMs int64 `sql:"primary_key"`
}
