//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TotpUserDevices struct {
	AppID      string `sql:"primary_key"`
	UserID     string `sql:"primary_key"`
	DeviceName string `sql:"primary_key"`
	SecretKey  string
	Period     int32
	Skew       int32
	Verified   bool
}
