//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Transaction struct {
	ID          string `sql:"primary_key"`
	UserID      string
	Amount      float64
	Date        int64
	CategoryID  string
	Description *string
	IsExpense   bool
	CreatedAt   int64
	UpdatedAt   int64
}
